GET http://localhost:3000/users

###
POST  http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Mojje",
    "password" : "Mojtaba"

}

###
POST  http://localhost:3000/users/loging
Content-Type: application/json

{
    "name" : "Mojje",
    "password" : "Mojaba"

}